[package]
name = "optional-numeric-index"
description = " Traits and macros for creating compact optional numeric indices."
version = "0.3.5"
authors = ["Sebastian Schmidt <sebastian.schmidt@helsinki.fi>"]
license = "BSD-2-Clause"
repository = "https://github.com/sebschmi/optional-numeric-index"

edition = "2024"

[features]
zerocopy = ["dep:zerocopy"]

[dependencies]
num-traits = "0.2.19"
zerocopy = { version = "0.8.39", features = ["derive"], optional = true }
